services:
  ck:
    container_name: ck
    build:
      context: .
      platforms:
        - linux/arm64
    platform: linux/arm64
    environment:
      - PUID=1000
      - PGID=1000
      # Server configuration
      - WORLD_NAME=Core-Keeper-ARM64
      - WORLD_SEED=0
      - WORLD_MODE=0
      - MAX_PLAYERS=10
      - DATA_PATH=/home/steam/core-keeper-data
      - GAME_ID=${GAME_ID}
    volumes:
      - ./server-data:/home/steam/core-keeper-data:rw
    restart: unless-stopped